name: Magento
description: |
  Short description # Description of the Catalog Entry
version: 0.1
category: Applications
maintainer: Nikolay Bochev
projectURL: https://github.com/sh1ny/rancher-catalog
